/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ducky.dragdrop;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author NGUYENHOANGVANNHA
 */
public class RadioButtonDemo extends javax.swing.JFrame {

    /**
     * Creates new form RadioButtonDemo
     */
    public RadioButtonDemo() {
        this.setTitle("Radio Button Demo");
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(RadioButtonDemo.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rdVietNam = new javax.swing.JRadioButton();
        rdThaiLan = new javax.swing.JRadioButton();
        rdLao = new javax.swing.JRadioButton();
        bShow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rdVietNam);
        rdVietNam.setText("Viet Nam");
        rdVietNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdVietNamActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdThaiLan);
        rdThaiLan.setText("Thai Lan");
        rdThaiLan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdThaiLanActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdLao);
        rdLao.setText("Lao");

        bShow.setText("Show");
        bShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bShow)
                    .addComponent(rdLao)
                    .addComponent(rdThaiLan)
                    .addComponent(rdVietNam))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(rdVietNam)
                .addGap(18, 18, 18)
                .addComponent(rdThaiLan)
                .addGap(18, 18, 18)
                .addComponent(rdLao)
                .addGap(18, 18, 18)
                .addComponent(bShow)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdThaiLanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdThaiLanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdThaiLanActionPerformed

    private void rdVietNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdVietNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdVietNamActionPerformed

    private void bShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bShowActionPerformed
        // TODO add your handling code here:
        if(rdVietNam.isSelected()){
            JOptionPane.showMessageDialog(null, "Selected: " + rdVietNam.getText(), "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        if(rdThaiLan.isSelected()){
            JOptionPane.showMessageDialog(null, "Selected: " + rdThaiLan.getText(), "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        if(rdLao.isSelected()){
            JOptionPane.showMessageDialog(null, "Selected: " + rdLao.getText(), "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioButtonDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioButtonDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioButtonDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioButtonDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioButtonDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bShow;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rdLao;
    private javax.swing.JRadioButton rdThaiLan;
    private javax.swing.JRadioButton rdVietNam;
    // End of variables declaration//GEN-END:variables
}
