/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chap01.basic;

import javax.swing.JOptionPane;

/**
 *
 * @author NGUYENHOANGVANNHA
 */
public class TwoOperator extends javax.swing.JFrame {

    /**
     * Creates new form TwoOperator
     */
    public TwoOperator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private String operator = "Addition";
    private int number1 = 0;
    private int number2 = 0;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bExe = new javax.swing.JButton();
        tfNumber1 = new javax.swing.JTextField();
        tfNumber2 = new javax.swing.JTextField();
        tfResult = new javax.swing.JTextField();
        cbOperator = new javax.swing.JComboBox<>();
        bMax = new javax.swing.JButton();
        tfMax = new javax.swing.JTextField();
        bRandom = new javax.swing.JButton();
        tfRandom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbMonth = new javax.swing.JComboBox<>();
        tfMonth = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caculator");
        setLocation(new java.awt.Point(400, 50));

        jLabel1.setText("First Number");

        jLabel2.setText("Second Number");

        jLabel3.setText("Operator");

        bExe.setText("Excute");
        bExe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExeActionPerformed(evt);
            }
        });

        cbOperator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Addition", "Subtract", "Multiply", "Divide" }));
        cbOperator.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbOperatorItemStateChanged(evt);
            }
        });

        bMax.setText("Max");
        bMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMaxActionPerformed(evt);
            }
        });

        bRandom.setText("Random");
        bRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRandomActionPerformed(evt);
            }
        });

        jLabel5.setText("Month");

        cbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cbMonth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMonthItemStateChanged(evt);
            }
        });

        tfMonth.setText("31");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(bExe)
                    .addComponent(bMax, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRandom))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfResult, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfNumber1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfNumber2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbOperator, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tfMax, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRandom))
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbOperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bExe)
                    .addComponent(tfResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bMax)
                    .addComponent(tfMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRandom)
                    .addComponent(tfRandom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void getNumber(){
        try{
            number1 = Integer.parseInt(tfNumber1.getText());
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: " + e.toString(),"Caution",JOptionPane.ERROR_MESSAGE);
            tfNumber1.requestFocus();
            tfResult.setText("");
            tfMax.setText("");
            tfRandom.setText("");
            return;
        }
        try{
            number2 = Integer.parseInt(tfNumber2.getText());
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.toString(), "Caution", JOptionPane.ERROR_MESSAGE);
            tfNumber2.requestFocus();
            tfResult.setText("");
            tfMax.setText("");
            tfRandom.setText("");
            return;
        }
    }
    private void bExeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExeActionPerformed
        // TODO add your handling code here:
        
        
        getNumber();
        int result = 0;
        switch(operator){
            case "Addition": result = number1 + number2;
                break;
            case "Subtract": result = number1 - number2;
                break;
            case "Multiply": result = number1 * number2;
                break;
            case "Divide": result = (int)number1/number2;
                break;
        }
        tfResult.setText(Integer.toString(result));
    }//GEN-LAST:event_bExeActionPerformed

    private void cbOperatorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOperatorItemStateChanged
        // TODO add your handling code here:
        operator = (String)evt.getItem();
        tfMax.setText(operator);
    }//GEN-LAST:event_cbOperatorItemStateChanged

    private void bMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMaxActionPerformed
        // TODO add your handling code here:
        
        getNumber();
        
        tfMax.setText(Integer.toString(Math.max(number1, number2)));
    }//GEN-LAST:event_bMaxActionPerformed

    private void bRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRandomActionPerformed
        // TODO add your handling code here:
        
        getNumber();
        int max = Math.max(number1, number2);
        int min = Math.min(number1, number2);
        int random = (int)(Math.random()*(max - min + 1)) + min;
        tfRandom.setText(Integer.toString(random));
    }//GEN-LAST:event_bRandomActionPerformed

    private void cbMonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMonthItemStateChanged
        // TODO add your handling code here:
        int dates = 0;
        String month = (String)evt.getItem();
        int result = 31;
        switch(month){
            case "February": result = 28;
                break;
                
            case "January":
            case "March":
            case "May":
            case "July":
            case "August":
            case "October":
            case "December": result = 31;
                break;
            
            case "April":
            case "June":
            case "September":
            case "November": result = 30;
                break;
        }
        tfMonth.setText(Integer.toString(result));
    }//GEN-LAST:event_cbMonthItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwoOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwoOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwoOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwoOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwoOperator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExe;
    private javax.swing.JButton bMax;
    private javax.swing.JButton bRandom;
    private javax.swing.JComboBox<String> cbMonth;
    private javax.swing.JComboBox<String> cbOperator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfMax;
    private javax.swing.JTextField tfMonth;
    private javax.swing.JTextField tfNumber1;
    private javax.swing.JTextField tfNumber2;
    private javax.swing.JTextField tfRandom;
    private javax.swing.JTextField tfResult;
    // End of variables declaration//GEN-END:variables
}
