/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chap03.array;

import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author NGUYENHOANGVANNHA
 */
public class ArrayClass extends javax.swing.JFrame {

    /**
     * Creates new form ArrayBasic
     */
    public ArrayClass() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ArrayClass.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taShow = new javax.swing.JTextArea();
        btShow = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btAuto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfAddNew = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfElements = new javax.swing.JTextField();
        btNewArray = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btMax = new javax.swing.JButton();
        btMin = new javax.swing.JButton();
        tfMax = new javax.swing.JTextField();
        tfMin = new javax.swing.JTextField();
        btSum = new javax.swing.JButton();
        tfSum = new javax.swing.JTextField();
        btSortInc = new javax.swing.JButton();
        btSortDec = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Array Class");
        setLocation(new java.awt.Point(300, 80));

        taShow.setColumns(20);
        taShow.setRows(5);
        jScrollPane1.setViewportView(taShow);

        btShow.setText("Show");
        btShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btAuto.setText("Auto");
        btAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAutoActionPerformed(evt);
            }
        });

        jLabel1.setText("Add new");

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        jLabel2.setText("Elements");

        btNewArray.setText("new Array");
        btNewArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewArrayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfElements, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAdd)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btNewArray)
                        .addGap(18, 18, 18)
                        .addComponent(btAuto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfElements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNewArray)
                    .addComponent(btAuto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btMax.setText("Max");
        btMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaxActionPerformed(evt);
            }
        });

        btMin.setText("Min");
        btMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMinActionPerformed(evt);
            }
        });

        btSum.setText("Sum");
        btSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSumActionPerformed(evt);
            }
        });

        btSortInc.setText("Sort Inc");
        btSortInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSortIncActionPerformed(evt);
            }
        });

        btSortDec.setText("Sort dec");
        btSortDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSortDecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMax, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btSum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfSum, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btSortInc)
                                .addGap(18, 18, 18)
                                .addComponent(btSortDec)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMax)
                    .addComponent(tfMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMin)
                    .addComponent(tfMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSum)
                    .addComponent(tfSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSortInc)
                    .addComponent(btSortDec))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btShow)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btShow)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int number;
    private int[] arrInt;
    private void getArrayInfo(){
        try{
            number = Integer.parseInt(tfElements.getText());
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Wrong elements", "Warning", JOptionPane.WARNING_MESSAGE);
            tfElements.requestFocus();
            return;
        }
    }
    private void btNewArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewArrayActionPerformed
        // TODO add your handling code here:
        getArrayInfo();
        if(number >= 0) {
            arrInt = new int[number];
            JOptionPane.showMessageDialog(null, "Success!", "Notification", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Wrong elements", "Warning", JOptionPane.WARNING_MESSAGE);
            tfElements.requestFocus();
            return;
        }
    }//GEN-LAST:event_btNewArrayActionPerformed
    
    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        if(arrInt == null){
            JOptionPane.showMessageDialog(null, "Array does not exist!", "Warning", JOptionPane.WARNING_MESSAGE);
            tfMax.setText("");
            btNewArray.requestFocus();
            return;
        } else{
           try{
               arrInt = Arrays.copyOf(arrInt, arrInt.length + 1);
               arrInt[arrInt.length - 1] = Integer.parseInt(tfAddNew.getText());
               number++;
           } catch(Exception ex){
               JOptionPane.showMessageDialog(null, "Wrong element\n" + ex.toString(), "Warning", JOptionPane.WARNING_MESSAGE);
               tfAddNew.requestFocus();
               return;
           }
           JOptionPane.showMessageDialog(null, "Success!", "Notification", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAutoActionPerformed
        // TODO add your handling code here:
        if(arrInt == null) {
            JOptionPane.showMessageDialog(null, "You have to create a new array first!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else{
            for(int i = 0; i < number; i++){
                arrInt[i] = (int)(Math.random()*(number + number + 1)) - number;
            }
            JOptionPane.showMessageDialog(null,"Success!", "Notification",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btAutoActionPerformed

    private void btShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowActionPerformed
        // TODO add your handling code here:
//        StringBuilder stb = new StringBuilder();
//        for(int i = 0; i < number; i++){
//            stb.append(arrInt[i] + " ");
//            if(((i+1) % 20) == 0) stb.append("\n");
//        }
        taShow.setText(Arrays.toString(arrInt));
    }//GEN-LAST:event_btShowActionPerformed

    private void btMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaxActionPerformed
        // TODO add your handling code here:
        if(arrInt == null){
            JOptionPane.showMessageDialog(null, "Array does not exist!", "Warning", JOptionPane.WARNING_MESSAGE);
            tfMax.setText("");
            btNewArray.requestFocus();
        } else{
            int max = 0;
            for(int i = 0; i < arrInt.length; i++){
                if(arrInt[i] > max) max = arrInt[i];
            }
            tfMax.setText(Integer.toString(max));
        }
    }//GEN-LAST:event_btMaxActionPerformed

    private void btMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMinActionPerformed
        // TODO add your handling code here:
        if(arrInt == null){
            JOptionPane.showMessageDialog(null, "Array does not exist!", "Warning", JOptionPane.WARNING_MESSAGE);
            tfMax.setText("");
            btNewArray.requestFocus();
        } else{
            int min = 0;
            for(int i = 0; i < arrInt.length; i++){
                if(arrInt[i] < min) min = arrInt[i];
            }
            tfMin.setText(Integer.toString(min));
        }
    }//GEN-LAST:event_btMinActionPerformed

    private void btSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSumActionPerformed
        // TODO add your handling code here:
        if(arrInt == null){
            JOptionPane.showMessageDialog(null, "Array does not exist!", "Warning", JOptionPane.WARNING_MESSAGE);
            tfMax.setText("");
            btNewArray.requestFocus();
        } else{
            int sum = 0;
            for(int i = 0; i < arrInt.length; i++){
                sum += arrInt[i];
            }
            tfSum.setText(Integer.toString(sum));
        }
    }//GEN-LAST:event_btSumActionPerformed

    private void btSortIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSortIncActionPerformed
        // TODO add your handling code here:
        if(arrInt == null){
            JOptionPane.showMessageDialog(null, "Array does not exist!", "Warning", JOptionPane.WARNING_MESSAGE);
            btNewArray.requestFocus();
            return;
        } else{
            Arrays.sort(arrInt);
            JOptionPane.showMessageDialog(null, "Success!", "Notification", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btSortIncActionPerformed

    private void btSortDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSortDecActionPerformed
        // TODO add your handling code here:
        if(arrInt == null){
            JOptionPane.showMessageDialog(null, "Array does not exist!", "Warning", JOptionPane.WARNING_MESSAGE);
            btNewArray.requestFocus();
            return;
        } else{
            Arrays.sort(arrInt);
            int temp;
            for(int i = 0; i <= ((arrInt.length - 1) / 2); i++){
                temp = arrInt[arrInt.length - 1 - i];
                arrInt[arrInt.length - 1 - i] = arrInt[i];
                arrInt[i] = temp;
            }
            JOptionPane.showMessageDialog(null, "Success!", "Notification", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btSortDecActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArrayClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArrayClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArrayClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArrayClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArrayClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btAuto;
    private javax.swing.JButton btMax;
    private javax.swing.JButton btMin;
    private javax.swing.JButton btNewArray;
    private javax.swing.JButton btShow;
    private javax.swing.JButton btSortDec;
    private javax.swing.JButton btSortInc;
    private javax.swing.JButton btSum;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taShow;
    private javax.swing.JTextField tfAddNew;
    private javax.swing.JTextField tfElements;
    private javax.swing.JTextField tfMax;
    private javax.swing.JTextField tfMin;
    private javax.swing.JTextField tfSum;
    // End of variables declaration//GEN-END:variables
}
