/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chap05.string;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author NGUYENHOANGVANNHA
 */
public class StrREFrom extends javax.swing.JFrame {

    /**
     * Creates new form StrREFrom
     */
    public StrREFrom() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(StrREFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taInput = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        btToString = new javax.swing.JButton();
        btIsNumber = new javax.swing.JButton();
        btIsID = new javax.swing.JButton();
        btIUsername = new javax.swing.JButton();
        btReplace = new javax.swing.JButton();
        tfReplaceFrom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfReplaceTo = new javax.swing.JTextField();
        btReplaceAll = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Regular Expression");
        setLocation(new java.awt.Point(400, 60));

        jLabel1.setText("Input");

        taInput.setColumns(20);
        taInput.setRows(5);
        jScrollPane1.setViewportView(taInput);

        jLabel2.setText("Output");

        taOutput.setColumns(20);
        taOutput.setRows(5);
        jScrollPane2.setViewportView(taOutput);

        btToString.setText("to String");
        btToString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btToStringActionPerformed(evt);
            }
        });

        btIsNumber.setText("is Number");
        btIsNumber.setToolTipText("Check Input string is a number 0 < 100");
        btIsNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIsNumberActionPerformed(evt);
            }
        });

        btIsID.setText("is ID");
        btIsID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIsIDActionPerformed(evt);
            }
        });

        btIUsername.setText("is Username");
        btIUsername.setToolTipText("1. Tên đăng nhập phải bắt đầu bằng một ký tự hoặc dấu gạch dưới\n2. Tên đăng nhập là tập hợp của các ký tự a-z, 0-9 và có thể có các ký tự như dấu chấm ( . ), dấu gạch dưới ( _ )\n3. Độ dài tối thiểu của tên đăng nhập là là 5 ký tự và độ dài tối đa là 32 ký tự");
        btIUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIUsernameActionPerformed(evt);
            }
        });

        btReplace.setText("Replace");
        btReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReplaceActionPerformed(evt);
            }
        });

        jLabel3.setText("to");

        btReplaceAll.setText("Replace All");
        btReplaceAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReplaceAllActionPerformed(evt);
            }
        });

        jLabel4.setText("From or RE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btToString))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btIsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btIsID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btIUsername)
                        .addGap(95, 95, 95)
                        .addComponent(btReplace)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(btReplaceAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfReplaceFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tfReplaceTo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(btToString))))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btIsID)
                            .addComponent(btIUsername)
                            .addComponent(btIsNumber)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfReplaceFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btReplace)
                            .addComponent(btReplaceAll)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfReplaceTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String strIn, strOut;
    private String strFrom, strTo;
    private void btToStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btToStringActionPerformed
        // TODO add your handling code here:
        strIn = taInput.getText();
    }//GEN-LAST:event_btToStringActionPerformed

    private void btIsNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIsNumberActionPerformed
        // TODO add your handling code here:
        if(strIn == null){
            JOptionPane.showMessageDialog(null, "Please input a string", "Error", JOptionPane.ERROR_MESSAGE);
            btToString.requestFocus();
        } else{
            taOutput.setText(Boolean.toString(strIn.matches("\\d{1,2}")));
        }
    }//GEN-LAST:event_btIsNumberActionPerformed

    private void btIsIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIsIDActionPerformed
        // TODO add your handling code here:
        if(strIn == null){
            JOptionPane.showMessageDialog(null, "Please input a string", "Error", JOptionPane.ERROR_MESSAGE);
            btToString.requestFocus();
        } else{
            taOutput.setText(Boolean.toString(strIn.matches("[A-z]{3}-[2-8]{3}")));
        }
    }//GEN-LAST:event_btIsIDActionPerformed

//        1. Tên đăng nhập phải bắt đầu bằng một ký tự hoặc dấu gạch dưới
//        2. Tên đăng nhập là tập hợp của các ký tự a-z, 0-9 và có thể có các ký tự như dấu
//        chấm ( . ), dấu gạch dưới ( _ )
//        3. Độ dài tối thiểu của tên đăng nhập là là 5 ký tự và độ dài tối đa là 32 ký tự
    private void btIUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIUsernameActionPerformed
        // TODO add your handling code here:
        if(strIn == null){
            JOptionPane.showMessageDialog(null, "Please input a string", "Error", JOptionPane.ERROR_MESSAGE);
            btToString.requestFocus();
        } else{
            taOutput.setText(Boolean.toString(strIn.matches("[A-z_][a-z0-9\\._]{4,31}")));
        }
    }//GEN-LAST:event_btIUsernameActionPerformed

    private void btReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReplaceActionPerformed
        // TODO add your handling code here:
        if(strIn == null){
            JOptionPane.showMessageDialog(null, "Please input a string", "Error", JOptionPane.ERROR_MESSAGE);
            btToString.requestFocus();
        } else{
            strFrom = new String(tfReplaceFrom.getText());
            strTo = new String(tfReplaceTo.getText());
            if(strFrom.equals("") || strTo == null){
                JOptionPane.showMessageDialog(null, "Please fill 'From' and 'To'.", "Error", JOptionPane.ERROR_MESSAGE);
                tfReplaceFrom.requestFocus();
            } else{
                try{
                    strIn = strIn.replace(strFrom, strTo);
                } catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "May string does not exist to replace\n" + ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
                    tfReplaceFrom.requestFocus();
                    return;
                }
                taOutput.setText(strIn);
            }
            
        }
        
    }//GEN-LAST:event_btReplaceActionPerformed

    private void btReplaceAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReplaceAllActionPerformed
        // TODO add your handling code here:
        if(strIn == null){
            JOptionPane.showMessageDialog(null, "Please input a string", "Error", JOptionPane.ERROR_MESSAGE);
            btToString.requestFocus();
        } else {
            strFrom = new String(tfReplaceFrom.getText());
            strTo = new String(tfReplaceTo.getText());
            if(strFrom.isEmpty()){
                JOptionPane.showMessageDialog(null, "Please input a Regular Expression");
                tfReplaceFrom.requestFocus();
                return;
            } else {
                strIn = strIn.replaceAll(strFrom,strTo);
                taOutput.setText(strIn);
            }
        }
    }//GEN-LAST:event_btReplaceAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StrREFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StrREFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StrREFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StrREFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StrREFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIUsername;
    private javax.swing.JButton btIsID;
    private javax.swing.JButton btIsNumber;
    private javax.swing.JButton btReplace;
    private javax.swing.JButton btReplaceAll;
    private javax.swing.JButton btToString;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taInput;
    private javax.swing.JTextArea taOutput;
    private javax.swing.JTextField tfReplaceFrom;
    private javax.swing.JTextField tfReplaceTo;
    // End of variables declaration//GEN-END:variables
}
