/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chap05.string;

import java.util.Arrays;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author NGUYENHOANGVANNHA
 */
public class StrSplit extends javax.swing.JFrame {

    /**
     * Creates new form StrSplit
     */
    public StrSplit() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(StrSplit.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taInput = new javax.swing.JTextArea();
        btToString = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btScannerSplit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btScannerSplitWith = new javax.swing.JButton();
        tfScannerSplit = new javax.swing.JTextField();
        btREScannerSplit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        taOut = new javax.swing.JTextArea();
        btSplit = new javax.swing.JButton();
        tfSplit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btStringTokenizer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfStringTokenizer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        taOutput.setColumns(20);
        taOutput.setRows(5);
        jScrollPane2.setViewportView(taOutput);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Slit String");
        setLocation(new java.awt.Point(400, 70));

        jLabel1.setText("Input");

        taInput.setColumns(20);
        taInput.setRows(5);
        jScrollPane1.setViewportView(taInput);

        btToString.setText("To String");
        btToString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btToStringActionPerformed(evt);
            }
        });

        jLabel2.setText("Output");

        btScannerSplit.setText("Scanner Split");
        btScannerSplit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btScannerSplitActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btScannerSplitWith.setText("Scanner Split With");
        btScannerSplitWith.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btScannerSplitWithActionPerformed(evt);
            }
        });

        btREScannerSplit.setText("RE Scanner Split");
        btREScannerSplit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btREScannerSplitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btScannerSplitWith)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btREScannerSplit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfScannerSplit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btScannerSplitWith)
                    .addComponent(tfScannerSplit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btREScannerSplit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        taOut.setColumns(20);
        taOut.setRows(5);
        jScrollPane3.setViewportView(taOut);

        btSplit.setText("Split");
        btSplit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSplitActionPerformed(evt);
            }
        });

        tfSplit.setToolTipText("Fill a regular expression or a ");

        jLabel3.setText("Regex");

        btStringTokenizer.setText("StringTokenizer");
        btStringTokenizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStringTokenizerActionPerformed(evt);
            }
        });

        jLabel4.setText("Demiliter");

        jLabel5.setText("(Not support Regular expression)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btToString)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btScannerSplit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSplit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfSplit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btStringTokenizer)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfStringTokenizer, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(127, 127, 127)
                        .addComponent(btScannerSplit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btToString)
                                .addComponent(jLabel2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSplit)
                    .addComponent(jLabel3)
                    .addComponent(tfSplit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btStringTokenizer)
                    .addComponent(jLabel4)
                    .addComponent(tfStringTokenizer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String strInput;
    private StringBuilder strOutput;
    private String demiliter;
    private String regex;
    private void btToStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btToStringActionPerformed
        // TODO add your handling code here:
        strInput = taInput.getText();
        if(strInput.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill a string", "Error", JOptionPane.ERROR_MESSAGE);
            taInput.requestFocus();
            return;
        }
    }//GEN-LAST:event_btToStringActionPerformed

    private void btScannerSplitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btScannerSplitActionPerformed
        // TODO add your handling code here:
        if(strInput == null){
            JOptionPane.showMessageDialog(null, "Please fill a string", "Error", JOptionPane.ERROR_MESSAGE);
            btToString.requestFocus();
            return;
        } else {
            Scanner sc = new Scanner(strInput);
            strOutput = new StringBuilder();
            while(sc.hasNext()){
                strOutput.append(sc.next() + "\n");
            }
            taOut.setText(strOutput.toString());
        }
    }//GEN-LAST:event_btScannerSplitActionPerformed

    private void btScannerSplitWithActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btScannerSplitWithActionPerformed
        // TODO add your handling code here:
        if(strInput == null){
            JOptionPane.showMessageDialog(null, "Please fill a string", "Error", JOptionPane.ERROR_MESSAGE);
            btToString.requestFocus();
            return;
        } else {
            demiliter = tfScannerSplit.getText();
            Scanner sc = new Scanner(strInput);
            sc.useDelimiter(demiliter);
            strOutput = new StringBuilder();
            while(sc.hasNext()){
                strOutput.append(sc.next() + "\n");
            }
            taOut.setText(strOutput.toString());
        }
    }//GEN-LAST:event_btScannerSplitWithActionPerformed

    private void btREScannerSplitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btREScannerSplitActionPerformed
        // TODO add your handling code here:
        if(strInput == null){
            JOptionPane.showMessageDialog(null, "Please fill a string", "Error", JOptionPane.ERROR_MESSAGE);
            btToString.requestFocus();
            return;
        } else {
            demiliter = tfScannerSplit.getText();
            Scanner sc = new Scanner(strInput);
            sc.useDelimiter(demiliter);
            strOutput = new StringBuilder();
            while(sc.hasNext()){
                strOutput.append(sc.next() + "\n");
            }
            taOut.setText(strOutput.toString());
        }
    }//GEN-LAST:event_btREScannerSplitActionPerformed

    private void btSplitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSplitActionPerformed
        // TODO add your handling code here:
        if(strInput == null){
            JOptionPane.showMessageDialog(null, "Please fill a string", "Error", JOptionPane.ERROR_MESSAGE);
            btToString.requestFocus();
            return;
        } else {
            regex = tfSplit.getText();
            String[] arrStr = strInput.split(regex);
            strOutput = new StringBuilder();
            //taOut.setText(Arrays.toString(arrStr));
            for(int i = 0; i < arrStr.length; i++){
                strOutput.append(arrStr[i] + "\n");
            }
            taOut.setText(strOutput.toString());
        }
    }//GEN-LAST:event_btSplitActionPerformed

    private void btStringTokenizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStringTokenizerActionPerformed
        // TODO add your handling code here:
        if(strInput == null){
            JOptionPane.showMessageDialog(null, "Please fill a string", "Error", JOptionPane.ERROR_MESSAGE);
            btToString.requestFocus();
            return;
        } else {
            demiliter = tfStringTokenizer.getText();
            StringTokenizer strTokenizerObj = new StringTokenizer(strInput, demiliter);
            strOutput = new StringBuilder();
            while(strTokenizerObj.hasMoreTokens()){
                strOutput.append(strTokenizerObj.nextToken() + "\n");
            }
            taOut.setText(strOutput.toString());
        }
    }//GEN-LAST:event_btStringTokenizerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StrSplit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StrSplit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StrSplit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StrSplit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StrSplit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btREScannerSplit;
    private javax.swing.JButton btScannerSplit;
    private javax.swing.JButton btScannerSplitWith;
    private javax.swing.JButton btSplit;
    private javax.swing.JButton btStringTokenizer;
    private javax.swing.JButton btToString;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea taInput;
    private javax.swing.JTextArea taOut;
    private javax.swing.JTextArea taOutput;
    private javax.swing.JTextField tfScannerSplit;
    private javax.swing.JTextField tfSplit;
    private javax.swing.JTextField tfStringTokenizer;
    // End of variables declaration//GEN-END:variables
}
